services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/aarya526/WebHive-PHP.git
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-user
      - key: DB_PASSWORD
        value: your-database-password
